name: "socialmedia-service"

services:
  api-gateway:
    build: ./api-gateway
    ports:
      - 3000:8000
    env_file:
      - ./api-gateway/.env
    depends_on:
      rabbitmq:
        condition: service_healthy
      redis:
        condition: service_started
      mongodb:
        condition: service_healthy
    environment:
      - REDIS_URL=redis://redis:6379
      - RABBITMQ_URL=amqp://rabbitmq:5672
      - MONGODB_URL=mongodb://admin:secret@mongodb:27017/socialmedia
    networks:
      - socialmedia-network

  auth-service:
    build: ./auth-service
    env_file:
      - ./auth-service/.env
    depends_on:
      rabbitmq:
        condition: service_healthy
      redis:
        condition: service_started
      mongodb:
        condition: service_healthy
    environment:
      - REDIS_URL=redis://redis:6379
      - RABBITMQ_URL=amqp://rabbitmq:5672
      - MONGODB_URL=mongodb://admin:secret@mongodb:27017/socialmedia
    networks:
      - socialmedia-network

  post-service:
    build: ./post-service
    env_file:
      - ./post-service/.env
    depends_on:
      rabbitmq:
        condition: service_healthy
      redis:
        condition: service_started
      mongodb:
        condition: service_healthy
    environment:
      - REDIS_URL=redis://redis:6379
      - RABBITMQ_URL=amqp://rabbitmq:5672
      - MONGODB_URL=mongodb://admin:secret@mongodb:27017/socialmedia
    networks:
      - socialmedia-network

  media-service:
    build: ./media-service
    env_file:
      - ./media-service/.env
    depends_on:
      rabbitmq:
        condition: service_healthy
      redis:
        condition: service_started
      mongodb:
        condition: service_healthy
    environment:
      - REDIS_URL=redis://redis:6379
      - RABBITMQ_URL=amqp://rabbitmq:5672
      - MONGODB_URL=mongodb://admin:secret@mongodb:27017/socialmedia
    networks:
      - socialmedia-network

  search-service:
    build: ./search-service
    env_file:
      - ./search-service/.env
    depends_on:
      rabbitmq:
        condition: service_healthy
      redis:
        condition: service_started
      mongodb:
        condition: service_healthy
    environment:
      - REDIS_URL=redis://redis:6379
      - RABBITMQ_URL=amqp://rabbitmq:5672
      - MONGODB_URL=mongodb://admin:secret@mongodb:27017/socialmedia
    networks:
      - socialmedia-network

  redis:
    image: redis:alpine
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - socialmedia-network

  rabbitmq:
    image: rabbitmq:3-management
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 30s
      timeout: 10s
      retries: 10
    networks:
      - socialmedia-network

  mongodb:
    image: mongo:6.0
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: secret
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.runCommand({ ping: 1 })"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - socialmedia-network
    volumes:
      - socialmedia-data:/data/db

networks:
  socialmedia-network:
    driver: bridge

volumes:
  socialmedia-data:
    driver: local
  redis_data:
    driver: local
